// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emuoffncjrrxznhqttsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdW9mZm5janJyeHpuaHF0dHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MTczNjAsImV4cCI6MjA3MjQ5MzM2MH0.w_Ds2uCzbjvcwneKqri49cPvMZ5u0Soxn-xnpGur7DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});